version: "3.1"
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: testUser
      POSTGRES_DB: test
    ports:
      - "5432:5432"
#  igd-account-service:
#      image: saman/igd-account-service
#      depends_on:
#        - "postgres-db"
#      ports:
#        - "8081:8080"
#      environment:
#        R2DBC_USER: testUser
#        R2DBC_PASS: password
#        R2DBC_URL: r2dbc:postgresql://postgres-db:5432/test
#  start_db:
#    image: dadarek/wait-for-dependencies
#    depends_on:
#      - "postgres-db"
#    command: postgres-db:5432